{% set name = "qsharp-core" %}
{% set version = "0.26.233415" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qsharp-core-{{ version }}.tar.gz
    sha256: c095469279b88949320a0a4a32d6e1b62f8b759cdae8dcb396187bf246c3cfac
  - url: https://raw.githubusercontent.com/microsoft/iqsharp/release/v{{ version }}/LICENSE
    sha256: dea9265341829002e2c23a7372393eb2ed6e26085fb623f38a4ba0af833f30a6
  - url: https://raw.githubusercontent.com/microsoft/iqsharp/release/v{{ version }}/NOTICE.txt
    sha256: cac5509911821f61ce5f69202f7fe16f98c1bec4ebb8dfdc4611b0f71b00946a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  script_env:
    - QSHARP_PY_CLIENT=mock
    - PYTHON_VERSION={{ version }}

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - jupyter_client >=7.3.4
    - python >=3.6

test:
  imports:
    - qsharp
  commands:
    - pip check
  requires:
    - pip


about:
  home: https://github.com/microsoft/iqsharp
  summary: Python client for Q#, a domain-specific quantum programming language
  license: MIT
  license_file:
    - LICENSE
    - NOTICE.txt
  dev_url: https://github.com/microsoft/iqsharp/tree/main/src/Python/qsharp-core

extra:
  recipe-maintainers:
    - BastianZim
