{% set name = "qsharp-core" %}
{% set version = "0.25.218240" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qsharp-core-{{ version }}.tar.gz
    sha256: 5a7fde168279d639018e0507582c926dd979ce965194621d2c3b146387645e2a
  - url: https://raw.githubusercontent.com/microsoft/iqsharp/release/v{{ version }}/LICENSE
    sha256: dea9265341829002e2c23a7372393eb2ed6e26085fb623f38a4ba0af833f30a6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  script_env:
    - QSHARP_PY_CLIENT=mock
    - PYTHON_VERSION={{ version }}

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - traitlets !=5.2.2
    - jupyter_client <7.0
    - python >=3.6
    - pyzmq <20.0.0

test:
  imports:
    - qsharp
  commands:
    - pip check
  requires:
    - pip


about:
  home: https://github.com/microsoft/iqsharp
  summary: Python client for Q#, a domain-specific quantum programming language
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/microsoft/iqsharp/tree/main/src/Python/qsharp-core

extra:
  recipe-maintainers:
    - BastianZim
